# Outputs for SkillPath Platform Infrastructure

# VPC Outputs
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

# EKS Outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN associated with EKS cluster"
  value       = module.eks.cluster_iam_role_arn
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
  sensitive   = true
}

output "cluster_version" {
  description = "The Kubernetes version for the EKS cluster"
  value       = module.eks.cluster_version
}

# Node Groups Outputs
output "node_groups" {
  description = "EKS node groups"
  value       = module.eks.node_groups
}

output "node_security_group_id" {
  description = "ID of the node shared security group"
  value       = module.eks.node_security_group_id
}

# Monitoring Outputs
output "prometheus_endpoint" {
  description = "Prometheus endpoint URL"
  value       = var.enable_monitoring ? module.monitoring[0].prometheus_endpoint : null
}

output "grafana_endpoint" {
  description = "Grafana endpoint URL"
  value       = var.enable_monitoring ? module.monitoring[0].grafana_endpoint : null
}

output "grafana_admin_password" {
  description = "Grafana admin password"
  value       = var.enable_monitoring ? module.monitoring[0].grafana_admin_password : null
  sensitive   = true
}

# Application Load Balancer
output "alb_dns_name" {
  description = "DNS name of the load balancer"
  value       = module.eks.alb_dns_name
}

output "alb_zone_id" {
  description = "Zone ID of the load balancer"
  value       = module.eks.alb_zone_id
}

# Kubernetes Configuration
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name     = module.eks.cluster_id
    cluster_endpoint = module.eks.cluster_endpoint
    cluster_ca_data  = module.eks.cluster_certificate_authority_data
    aws_region       = var.aws_region
  }
  sensitive = true
}

# Environment Information
output "environment" {
  description = "Environment name"
  value       = var.environment
}

output "aws_region" {
  description = "AWS region"
  value       = var.aws_region
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = local.cluster_name
}

# Application URLs
output "application_url" {
  description = "Application URL"
  value       = var.domain_name != "" ? "https://${var.domain_name}" : "http://${module.eks.alb_dns_name}"
}

output "api_url" {
  description = "API URL"
  value       = var.domain_name != "" ? "https://api.${var.domain_name}" : "http://${module.eks.alb_dns_name}/api"
}

# Lab Environment Configuration
output "lab_configuration" {
  description = "Lab environment configuration"
  value = {
    timeout_minutes      = var.lab_timeout_minutes
    max_concurrent_labs  = var.max_concurrent_labs
    node_group_labs      = "labs"
  }
}

# Backup and Monitoring Configuration
output "operational_config" {
  description = "Operational configuration"
  value = {
    backup_retention_days = var.backup_retention_days
    log_retention_days    = var.log_retention_days
    monitoring_enabled    = var.enable_monitoring
  }
}