apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillpath-web
  labels:
    app: skillpath
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skillpath
      component: web
  template:
    metadata:
      labels:
        app: skillpath
        component: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
      - name: web
        image: skillpath:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: supabase-url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: supabase-anon-key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: supabase-service-role-key
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: clerk-publishable-key
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: clerk-secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: skillpath-secrets
              key: openai-api-key
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.next/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: skillpath-web
  labels:
    app: skillpath
    component: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: skillpath
    component: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillpath-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
spec:
  rules:
  - host: skillpath.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skillpath-web
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: skillpath-secrets
type: Opaque
stringData:
  supabase-url: "PLACEHOLDER"
  supabase-anon-key: "PLACEHOLDER"
  supabase-service-role-key: "PLACEHOLDER"
  clerk-publishable-key: "PLACEHOLDER"
  clerk-secret-key: "PLACEHOLDER"
  openai-api-key: "PLACEHOLDER"